// Generated by freight. Do not edit.
//
// ManagedDownloaderExtension supplies a default implementation for every
// requirement, so this target needs no logic — but it must exist: without an
// embedded downloader extension, AssetPackManager traps at first use.

import BackgroundAssets
import ExtensionFoundation

@main
struct FreightDownloaderExtension: ManagedDownloaderExtension {}
