// Generated by freight. Do not edit.
//
// Assets are staged into src/main/assets by "freight build", from the root
// declared for this pack in freight.yaml.

plugins {
    id("com.android.asset-pack")
}

assetPack {
    packName.set("tutorial")
    dynamicDelivery {
        deliveryType.set("fast-follow")
    }
}
