import 'dart:io';

import 'package:path/path.dart' as p;

import '../pack_config.dart';
import '../pack_planner.dart';

/// Play's name for a [DeliveryPolicy].
///
/// The three map one to one, which is what lets one `freight.yaml` describe
/// both platforms.
String deliveryTypeOf(DeliveryPolicy policy) => switch (policy) {
  DeliveryPolicy.essential => 'install-time',
  DeliveryPolicy.prefetch => 'fast-follow',
  DeliveryPolicy.onDemand => 'on-demand',
};

/// What generating the modules changed.
final class AssetPackModules {
  const AssetPackModules({required this.created, required this.modified});

  final List<String> created;
  final List<String> modified;
}

/// Generates a Gradle asset pack module per pack and wires it into the build.
///
/// Idempotent: an existing module is left alone and the Gradle edits are only
/// made when the entry is not already there.
AssetPackModules generateAssetPackModules({
  required String projectRoot,
  required FreightConfig config,
}) {
  final androidDirectory = p.join(projectRoot, 'android');
  if (!Directory(androidDirectory).existsSync()) {
    throw AndroidSetupException('no android/ directory at $androidDirectory');
  }

  final created = <String>[];
  final modified = <String>[];

  for (final pack in config.packs) {
    final moduleDirectory = p.join(androidDirectory, pack.id);
    final buildFile = File(p.join(moduleDirectory, 'build.gradle.kts'));

    Directory(
      p.join(moduleDirectory, 'src', 'main', 'assets'),
    ).createSync(recursive: true);

    if (!buildFile.existsSync()) {
      buildFile.writeAsStringSync(_moduleBuildFile(pack));
      created.add(buildFile.path);
    }

    // Staged assets are build output that happens to live in the source tree,
    // because Gradle only reads them from the conventional location.
    final ignore = File(p.join(moduleDirectory, '.gitignore'));
    if (!ignore.existsSync()) {
      ignore.writeAsStringSync(
        '# Staged by "freight build" from the pack root in freight.yaml.\n'
        'src/main/assets/\n',
      );
      created.add(ignore.path);
    }
  }

  if (_wireSettings(androidDirectory, config)) {
    modified.add(p.join(androidDirectory, 'settings.gradle.kts'));
  }
  if (_wireApp(androidDirectory, config)) {
    modified.add(p.join(androidDirectory, 'app', 'build.gradle.kts'));
  }

  return AssetPackModules(created: created, modified: modified);
}

/// Copies each pack's files into its module, under the logical paths the app
/// reads back.
///
/// Play only reads assets from `src/main/assets`, so the files are staged there
/// rather than read from wherever the sources live. Copying costs disk, but it
/// is what keeps a pack's logical paths identical to the iOS archive's.
List<String> stageAssetPacks({
  required String projectRoot,
  required List<PackPlan> plans,
}) {
  final staged = <String>[];

  for (final plan in plans) {
    final assets = Directory(
      p.join(projectRoot, 'android', plan.config.id, 'src', 'main', 'assets'),
    );
    // Cleared first: a file dropped from the globs would otherwise linger in
    // the pack for as long as the module directory survives.
    if (assets.existsSync()) assets.deleteSync(recursive: true);
    assets.createSync(recursive: true);

    for (final file in plan.files) {
      final destination = File(p.join(assets.path, file));
      destination.parent.createSync(recursive: true);
      File(p.join(plan.rootDirectory, file)).copySync(destination.path);
    }
    staged.add(assets.path);
  }

  return staged;
}

/// A project that cannot be set up for Play Asset Delivery.
final class AndroidSetupException implements Exception {
  const AndroidSetupException(this.message, {this.fix});

  final String message;
  final String? fix;

  @override
  String toString() => fix == null ? message : '$message\n$fix';
}

String _moduleBuildFile(PackConfig pack) => '''
// Generated by freight. Do not edit.
//
// Assets are staged into src/main/assets by "freight build", from the root
// declared for this pack in freight.yaml.

plugins {
    id("com.android.asset-pack")
}

assetPack {
    packName.set("${pack.id}")
    dynamicDelivery {
        deliveryType.set("${deliveryTypeOf(pack.delivery)}")
    }
}
''';

bool _wireSettings(String androidDirectory, FreightConfig config) {
  final file = File(p.join(androidDirectory, 'settings.gradle.kts'));
  if (!file.existsSync()) {
    throw AndroidSetupException(
      'no settings.gradle.kts at ${file.path}',
      fix: 'freight expects the layout flutter create produces.',
    );
  }

  var contents = file.readAsStringSync();
  var changed = false;

  // The asset pack plugin ships with the Android Gradle plugin, so it takes
  // whatever version the project already resolved for AGP rather than one this
  // tool picks.
  if (!contents.contains('com.android.asset-pack')) {
    final agp = RegExp(
      r'id\("com\.android\.application"\)\s+version\s+"([^"]+)"',
    ).firstMatch(contents);
    if (agp == null) {
      throw const AndroidSetupException(
        'settings.gradle.kts does not declare com.android.application, so the '
        'Android Gradle plugin version could not be determined',
        fix: 'Add id("com.android.asset-pack") to the plugins block yourself.',
      );
    }
    // After the whole line, not after the version match: the declaration
    // already ends in "apply false", and inserting mid-line duplicates it.
    final lineEnd = contents.indexOf('\n', agp.end);
    final anchor = lineEnd == -1 ? contents.length : lineEnd;
    contents = contents.replaceRange(
      anchor,
      anchor,
      '\n    id("com.android.asset-pack") version "${agp.group(1)}" apply false',
    );
    changed = true;
  }

  for (final pack in config.packs) {
    final include = 'include(":${pack.id}")';
    if (!contents.contains(include)) {
      contents = '${contents.trimRight()}\n$include\n';
      changed = true;
    }
  }

  if (changed) file.writeAsStringSync(contents);
  return changed;
}

bool _wireApp(String androidDirectory, FreightConfig config) {
  final file = File(p.join(androidDirectory, 'app', 'build.gradle.kts'));
  if (!file.existsSync()) {
    throw AndroidSetupException('no app/build.gradle.kts at ${file.path}');
  }

  final contents = file.readAsStringSync();
  final missing = [
    for (final pack in config.packs)
      if (!contents.contains('":${pack.id}"')) pack.id,
  ];
  if (missing.isEmpty) return false;

  final androidBlock = contents.indexOf('android {');
  if (androidBlock == -1) {
    throw const AndroidSetupException(
      'app/build.gradle.kts has no android block',
    );
  }
  final insertAt = contents.indexOf('\n', androidBlock) + 1;
  final entries = missing.map((id) => '":$id"').join(', ');

  file.writeAsStringSync(
    contents.replaceRange(
      insertAt,
      insertAt,
      '    assetPacks += listOf($entries)\n',
    ),
  );
  return true;
}
