// Generated by freight. Do not edit.
//
// Managed Background Assets supplies a default implementation for every
// requirement of ManagedDownloaderExtension — which downloads to schedule, how
// to authenticate, what to do on success and failure. The extension target has
// to exist and ship inside the app, but it needs no logic of its own.
//
// Override shouldDownload(_:) here if some packs should be skipped on this
// device.

import BackgroundAssets
import ExtensionFoundation

@main
struct FreightDownloaderExtension: ManagedDownloaderExtension {}
